sonar.projectKey=financial-control
sonar.projectName=Financial Control

sonar.host.url=http://localhost:60000
sonar.token=

sonar.sources=src/app
sonar.tests=src/app

sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/financial-control/lcov.info

sonar.sourceEncoding=UTF-8